# Generated by Django 5.1 on 2024-09-25 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='project',
            name='urlIntro',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
