# Generated by Django 5.1 on 2024-09-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_options_project_urlintro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='urlIntro',
            field=models.TextField(blank=True),
        ),
    ]
