# Generated by Django 5.1 on 2024-09-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_urlintro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='urlIntro',
        ),
        migrations.AddField(
            model_name='project',
            name='urlintro',
            field=models.CharField(blank=True, choices=[('repo', 'The repo for this can be found '), ('video', 'The video for this can be found '), ('link', 'The link for this can be found ')], max_length=50),
        ),
    ]
