# Generated by Django 5.1 on 2024-09-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_urlintro_project_urlintro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='urlintro',
            field=models.CharField(blank=True, choices=[('repo', 'The repo for this can be found '), ('video', 'The video for this can be found '), ('link', 'The link for this can be found ')], max_length=100),
        ),
    ]
